# Generated by Django 2.2.13 on 2020-09-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Lep name')),
                ('color', models.CharField(blank=True, max_length=10, null=True, verbose_name='Color')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Region name')),
                ('color', models.CharField(blank=True, max_length=10, null=True, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
            ],
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Pole name')),
                ('color', models.CharField(blank=True, max_length=10, null=True, verbose_name='Color')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('lep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyse.Lep')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Original name')),
                ('generated_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Generated name')),
                ('server_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Server name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lep_images')),
                ('is_sent_to_server', models.BooleanField(default=True, verbose_name='Is sent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('pole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyse.Pole')),
            ],
        ),
        migrations.AddField(
            model_name='lep',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyse.Region'),
        ),
    ]
