# Generated by Django 2.2.13 on 2020-09-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0003_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='photo',
            name='full_address',
            field=models.TextField(max_length=1000, null=True, verbose_name='Region name'),
        ),
        migrations.AddField(
            model_name='photo',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='photo',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='photo',
            name='pole_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pole name'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
