# Generated by Django 2.2.13 on 2020-09-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0004_auto_20200912_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='task_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Task ID'),
        ),
    ]
