# Generated by Django 2.2.13 on 2020-09-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0006_photo_photo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lep_small'),
        ),
    ]
